### ISSUE TITLE
Request for co-maintainership

### ISSUE THREAD

**Issue by quicksketch** [alexfinnarn/backdrop-xml-sitemap#105]
Hi @laryn, I'm using this module on a project and would like to help address some of the current issues in the queue. Would you be willing to add me as a (temporary) co-maintainer?

**Comment by quicksketch** [comment]
Had a little hiccup and made a PR against my own sandbox. Here's a PR for adding if Laryn approves: https://github.com/backdrop-contrib/xmlsitemap/pull/106

**Comment by laryn** [comment]
Gladly!

**Comment by quicksketch** [comment]
Thank you! :handshake:
