### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function `config_get()` in xmlsitemap.drush.inc (line 37)

### ISSUE THREAD

**Issue by jenlampton** [alexfinnarn/backdrop-xml-sitemap#109]
After updating to the latest version ([1.x-1.0.7](https://github.com/backdrop-contrib/xmlsitemap/releases/tag/1.x-1.0.7)), I get the following fatal error when running `drush updb`

```
Fatal error: Uncaught Error: Call to undefined function config_get() in backdrop/modules/contrib/xmlsitemap/xmlsitemap.drush.inc:37
```

**Comment by laryn** [comment]
Thanks @jenlampton -- tested, merged and cut a new release.
