### ISSUE TITLE
Google Submission URL has changed

### ISSUE THREAD

**Issue by Wylbur** [alexfinnarn/backdrop-xml-sitemap#114]
https://www.drupal.org/project/xmlsitemap/issues/3098810

This is related to #112 . 

The google url has changed from: 
https://www.google.com/webmasters/tools/ping?sitemap=[sitemap]
to 
https://www.google.com/ping?sitemap=[sitemap]

**Comment by quicksketch** [comment]
Thanks @Wylbur! I updated the URL in this commit: https://github.com/backdrop-contrib/xmlsitemap/commit/c749fb1de1867195496a7236263e738720eae0a7

It will be in 1.0.9
