### ISSUE TITLE
Skip pages that have 301 redirects set - setting persists, but the current form value is not correct

### ISSUE THREAD

**Issue by Wylbur** [alexfinnarn/backdrop-xml-sitemap#115]
When configuring the module, I check the "Skip pages that have 301 redirects set." setting, and save the settings.  
However, when the setting page is refreshed, that item is not checked.  

Next I checked the settings file.  Checking the box and saving does add a value in the module configuration -  "xmlsitemap_redirect": 1, so the checkbox is working and changes the module's configuration.  

When the page reloads, the checkbox is always unchecked.  Saving the form again does change the config file settings: "xmlsitemap_redirect": 0.

**Comment by yorkshire-pudding** [comment]
I get this error too

**Comment by quicksketch** [comment]
Thanks folks! I fixed this in https://github.com/backdrop-contrib/xmlsitemap/pull/119.
