### ISSUE TITLE
Update Readme to reflect removal of search engines

### ISSUE THREAD

**Issue by yorkshire-pudding** [alexfinnarn/backdrop-xml-sitemap#120]
a forum user has raised the issue that the readme mentions several search engines that it is no longer possible to submit to
https://forum.backdropcms.org/node/2901

Need to remove Bing, Ask and Yahoo

**Comment by quicksketch** [comment]
Thanks @yorkshire-pudding! Sounds good. Submitting sitemaps seems to be a disappearing concept.
