### ISSUE TITLE
Call to undefined function locale_language_list()

### ISSUE THREAD

**Issue by drupix** [alexfinnarn/backdrop-xml-sitemap#125]
With locale module enabled, the xmlsitemap_custom throw an error:

`Error : Call to undefined function locale_language_list() in xmlsitemap_custom_edit_link_form() (line 113 in xmlsitemap/xmlsitemap_custom/xmlsitemap_custom.admin.inc).`

[The `locale_language_list` function as been removed](https://docs.backdropcms.org/change-records/language_list-is-simplified-locale_language_list-is-removed).

I have just replaced locally the mentioned line from:
`$languages = module_exists('locale') ? locale_language_list() : array();`
to
`$languages = module_exists('locale') ? language_list(TRUE, TRUE, TRUE) : array();`
and it's work.

Is this correct? Can it be fixed?

**Comment by laryn** [comment]
Thanks for filing this issue @drupix! I ironed out a few other locale-related deprecations in the PR linked here. Are you able to test?

**Comment by drupix** [comment]
Hi @laryn, I'm little bit busy now, but I will have a look and test this week-end or next week.
Thanks.

**Comment by drupix** [comment]
Hi @laryn still a small issue, when I display the sitemap at mysite/[langcode]/sitemap.xml there is a warning:

`Warning: Undefined property: stdClass::$language in xmlsitemap_i18n_xmlsitemap_context() (line 40 of /webroot/modules/contrib/xmlsitemap/xmlsitemap_i18n/xmlsitemap_i18n.module).`

I think that `$context['language'] = $GLOBALS['language']->language;` must be replaced with `$context['language'] = $GLOBALS['language']->langcode;`

Otherwise I did not have any other issues!

**Comment by laryn** [comment]
Thanks for testing and finding that last piece to fix, @drupix -- I merged it. I was trying to figure out why the GHA checks weren't running and I think they were just outdated. I stole some code from @indigoxela and they are running again. The code checks didn't pass but that was all unrelated to these changes so I'll file another (separate) issue related to that. All the functional tests are passing.
