### ISSUE TITLE
Issue with sitemap.xsl stylesheet

### ISSUE THREAD

**Issue by alexfinnarn** [alexfinnarn/backdrop-xml-sitemap#18]
After creating a sitemap, I could see the file in the sitemap file directory with all the links I would expect, but when I went to view the "sitemap.xml" page in my browser it was blank. In the console log, I saw:

"error on line 138 at column 1: Extra content at the end of the document"

and that extra content appears to make the whole sitemap not render.

**Comment by jenlampton** [comment]
Interesting, I can actually see the errors in my browser window:
```
Error loading stylesheet: An unknown error has occurred (805303f4)
http://www.mysite.com/sitemap.xsl
```
But oddly enough, I see the same thing for my Drupal 7 site.

**Comment by jenlampton** [comment]
hm. If I rebuild the links and visit the new page, it works in Drupal 7. Must have been some kind of a cached issue. 

If I rebuild the links and visit the new page in backdrop, I see the following:
```
XML Parsing Error: junk after document element
Location: http://backdrop.mybackdropsite.com/sitemap.xsl
Line Number 138, Column 1:
```

**Comment by jenlampton** [comment]
Aha! It looks like we also need a backdrop_exit() in the xsl callback otherwise Backdrop tries to put it in a layout...

**Comment by jenlampton** [comment]
I put a commit that fixes this into https://github.com/alexfinnarn/backdrop-xml-sitemap/pull/19

**Comment by alexfinnarn** [comment]
adding backdrop_exit() fixed the xsl stylesheet issue for me, but the rest of #19 caused the sitemap to not regenerate so I committed this fix outside of that issue.
