### ISSUE TITLE
JS code still calling Drupal function

### ISSUE THREAD

**Issue by jenlampton** [alexfinnarn/backdrop-xml-sitemap#41]
When editing a node I'm unable to use the CKEditor link button.  A little text appears that says "loading" but nothing ever loads.

I see the following error in my console:
```
xmlsitemap.js?ounee6:6 Uncaught TypeError: $(...).drupalSetSummary is not a function
```

**Comment by jenlampton** [comment]
Hm, it looks like this was fixed back on April 14. Can we get a new release of xmlsitemap @alexfinnarn ?

**Comment by alexfinnarn** [comment]
Sure. Fixed in 1.x-1.0.1 release.
