### ISSUE TITLE
strange User notice error in logs

### ISSUE THREAD

**Issue by jenlampton** [alexfinnarn/backdrop-xml-sitemap#43]
In my log files I'm seeing the following PHP error
```
User notice:
array (
)
in xmlsitemap_node_xmlsitemap_index_links() (line 43 of backdrop/modules/contrib/xmlsitemap/xmlsitemap_node/xmlsitemap_node.module
```
noting here so I can diagnose later.

**Comment by alexfinnarn** [comment]
Any luck diagnosing @jenlampton? The line numbers have changed, and I'm not sure what is going on.

**Comment by jenlampton** [comment]
I haven't dug into it yet, but I'm seeing a different line number now too:
```
User notice: array ( ) in xmlsitemap_node_xmlsitemap_index_links() (line 56 of /backdrop/modules/contrib/xmlsitemap/xmlsitemap_node/xmlsitemap_node.module).
```

**Comment by alexfinnarn** [comment]
I tracked this down to the `debug($nids)` statement in that function. The attached PR just checks to see if the database query has results and then does the processing if so. 

This may have been a debugging statement that was never removed, but I'm not sure why a debug message needs to be logged every time the links are indexed.

It may be better to remove the debugging statement altogether, but it still makes sense to not call `xmlsitemap_node_xmlsitemap_process_node_links()` if there are no node IDs to check.

**Comment by jenlampton** [comment]
I'm still seeing the error in my logs. reopening.

```
User notice:
array (
)
in xmlsitemap_node_xmlsitemap_index_links() (line 81 of backdrop/modules/contrib/xmlsitemap/xmlsitemap_node/xmlsitemap_node.module).
```

**Comment by jenlampton** [comment]
Hm, the debug doesn't seem to be there in the latest 1.x. Maybe all we need is a new release?

**Comment by laryn** [comment]
New release has been made since last comment. Reopen if still an issue.
