### ISSUE TITLE
PHP Fatal error visiting Account settings page. 

### ISSUE THREAD

**Issue by bjoern-st** [alexfinnarn/backdrop-xml-sitemap#46]
Hey Alex.

First thank you for porting the module. 
I've installed it on a new project but unfortunately it throws an error.

Error message:
```
PHP Fatal error:  Unsupported operand types in /modules/contrib/xmlsitemap/xmlsitemap_user/xmlsitemap_user.module on line 128
```
I'm running PHP version 5.6.33 

Steps to reproduce:
 - Enable sub-module "XML sitemap user"
 - visit page /admin/config/people/settings

**Comment by alexfinnarn** [comment]
Hey @bjoern-st. Thanks for providing a great bug report with steps to reproduce and the error message! 

To be honest, I don't think I've ever turned on the sitemap user module in Drupal or Backdrop, but it looks like there used to be an array in the form on that page that doesn't exist anymore. 

https://github.com/backdrop-contrib/xmlsitemap/pull/47/files will show you that I just commented them out for now and the form loads and saves on admin/config/people/settings. 

All that code was doing is modifying where the email title and email fields would fall in the form order, so it might have just been an aesthetic choice for whatever reason. 

Do you think you can test that PR or just comment out those two lines and see what happens? This is definitely a critical bug for that submodule, but I'm unfortunately not sure what else it does enough to merge it in without more testing.

**Comment by bjoern-st** [comment]
Hey @alexfinnarn 
This is exactly what I did as hotfix and so I can confirm that it is working. 
Since there is only set the weight for some form elements I think you can leave these two lines without any risk.
