### ISSUE TITLE
The resource ... was blocked due to MIME type (“text/html”) mismatch

### ISSUE THREAD

**Issue by jenlampton** [alexfinnarn/backdrop-xml-sitemap#49]
when the `Include a stylesheet in the sitemaps for humans.` setting is enabled, I'm getting the following error on my sitemap.xml page:
```
Error loading stylesheet: A network error occurred loading an XSLT stylesheet:
```

Disabling the `Include a stylesheet in the sitemaps for humans.` setting makes the sitemap render as expected.

**Comment by alexfinnarn** [comment]
I don't see this behaviour, but I do see some JS errors.

![screen shot 2018-07-23 at 2 28 26 pm](https://user-images.githubusercontent.com/3640707/43101194-f81d5a10-8e84-11e8-9c00-6562f4f68f4f.png)

**Comment by jenlampton** [comment]
In the latest release, I'm now seeing:
```
Error loading stylesheet: An unknown error has occurred (805303f4)
```

And in the logs...
```
Warning: Cannot modify header information - headers already sent by (output started at backdrop/modules/contrib/xmlsitemap/xmlsitemap.pages.inc:117) in _backdrop_session_delete_cookie() (line 480 of backdrop/core/includes/session.inc).
```

**Comment by laryn** [comment]
I'm not seeing this on mine -- do you have any further info or STR?

**Comment by jenlampton** [comment]
Let's see...

* Backdrop 1.14.1
* xmlsitemap 1.x-1.0.5
* other modules enabled: XML sitemap menu, XML sitemap node
* checkbox for  Include a stylesheet in the sitemaps for humans.  

Weird, in Chrome today I see the JS errors @alexfinnarn reported...
```
The resource from “http://whatever.org/misc/jquery.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff)...sitemap.xml
ReferenceError: jQuery is not defined...jquery.tablesorter.min.js:2:2
ReferenceError: jQuery is not defined...xmlsitemap.xsl.js:44:1
```
But in my log I now see... 
```
page not found | Oct 24, 2019 | misc/jquery.js
```

I'm going to re-title this issue for the JS errors until I can reproduce this other issue reliably...

**Comment by laryn** [comment]
I think @BWPanda fixed this in https://github.com/backdrop-contrib/xmlsitemap/issues/96
