### ISSUE TITLE
An Undefined Constant: "BACKDROP_ANONYMOUS_RID"

### ISSUE THREAD

**Issue by alexfinnarn** [alexfinnarn/backdrop-xml-sitemap#52]
```
Notice: Use of undefined constant BACKDROP_ANONYMOUS_RID - assumed 'BACKDROP_ANONYMOUS_RID' in xmlsitemap_user_requirements() (line 19 of /app/modules/xmlsitemap/xmlsitemap_user/xmlsitemap_user.install).
```

**Comment by opi** [comment]
Change record https://api.backdropcms.org/change-records/converted-user-roles-cmi

> BACKDROP_ANONYMOUS_RID is now renamed to BACKDROP_ANONYMOUS_ROLE and is the value 'anonymous' instead of the integer 1.

**Comment by opi** [comment]
Corresponding PR to review & test https://github.com/backdrop-contrib/xmlsitemap/pull/53

**Comment by alexfinnarn** [comment]
Thanks, @opi! Reviewed and merged.
