### ISSUE TITLE
XML Sitemap User module

### ISSUE THREAD

**Issue by ghost** [alexfinnarn/backdrop-xml-sitemap#55]
If I have the XML Sitemap User sub-module disabled, I still see a 'User account' vertical tab on the `/admin/config/search/xmlsitemap/settings` page. This should be removed and only shown when the sub-module is enabled.

Also, when I do enable the sub-module, clicking on the 'User account' link under that vertical tab takes me to `/admin/config/people/manage` whereas it should take me to `/admin/config/people/settings` where the XML Sitemap settings are.

**Comment by alexfinnarn** [comment]
fixed by #42. I just tested and saw the tab when the user module was enabled and didn't see it when I disabled the module.
