### ISSUE TITLE
Remove 'XML sitemap' field from 'Manage Fields' page

### ISSUE THREAD

**Issue by ghost** [alexfinnarn/backdrop-xml-sitemap#56]
On the 'Manage Fields' page (admin/structure/types/manage/[CONTENT_TYPE]/fields) there's a 'field' for 'XML sitemap' which allows reordering but not configuration. This is pointless as the 'XML sitemap' field(s) on node forms are in a vertical tab and cannot be reordered. I suggest removing this for a cleaner UI.

**Comment by ghost** [comment]
Example:

![screenshot-2018-6-28 feature packweb](https://user-images.githubusercontent.com/2385329/42030184-a739fd82-7ada-11e8-81d3-d8c2e5fb0601.png)

![screenshot-2018-6-28 create feature packweb](https://user-images.githubusercontent.com/2385329/42030205-b13294de-7ada-11e8-9a18-04a6ae9382f4.png)
(the field covered by the admin bar is 'Icon')

**Comment by alexfinnarn** [comment]
![screen shot 2018-07-23 at 3 20 58 pm](https://user-images.githubusercontent.com/3640707/43103636-095525b8-8e8c-11e8-8914-adaec952454f.png)

Seems like other modules also follow this pattern so site builders might be familiar with seeing this...

It is done in the code here...
https://github.com/backdrop-contrib/xmlsitemap/blob/1.x-1.x/xmlsitemap_node/xmlsitemap_node.module#L154

I'm not sure what removing `xmlsitemap_node_field_extra_fields()` would do elsewhere in the module, though.

https://api.backdropcms.org/api/backdrop/core%21modules%21field%21field.api.php/function/hook_field_extra_fields/1

Thoughts?

**Comment by jenlampton** [comment]
> This is pointless as the 'XML sitemap' field(s) on node forms are in a vertical tab and cannot be reordered.

This setting does control the order of fields within the vertical tabs, as long as there are other orderable psuedo-fields in there to order them against. I often have Paging, Metatag, and XMLsitemap, all which have vertical tabs, and sometimes it's useful to order those.

That said, I'm not sure I'd miss the ordering of any of those vertical tabs if they all were to go.

**Comment by alexfinnarn** [comment]
I see what @jenlampton is saying about the ordering. My opinion would be to not change anything here. I can totally see some client saying "I want this field to show up above this other field in the form" and there's no real reason to change the code to make that task harder. Changing the code here would remove configuration without adding any real benefit.

**Comment by laryn** [comment]
I was noticing this same thing with Rabbit Hole and was going to try to get rid of it at some point because I find it annoying.

**Comment by jenlampton** [comment]
What if core added all the vertical tab options to this ordering form too, but maybe with a visual indicator that shows they would be separate from the other fields? That way it would be clearer when you only had one v-tab option that it wouldn't be ordered against the other non-v-tab options.

**Comment by laryn** [comment]
Closing this in favor of the core issue opened here:
https://github.com/backdrop/backdrop-issues/issues/4002
