### ISSUE TITLE
Drupal security release

### ISSUE THREAD

**Issue by kreynen** [alexfinnarn/backdrop-xml-sitemap#57]
https://www.drupal.org/sa-contrib-2018-053

Need to add make similar changes to https://github.com/CuBoulder/express/pull/2801/files#diff-3bbf127722c1bac6188e594cf607caf2R17 for the same reasons

**Comment by alexfinnarn** [comment]
Different tests are failing on this PR vs. the 1.x-1.x branch.

https://github.com/backdrop-contrib/xmlsitemap/blob/1.x-1.x/xmlsitemap_node/tests/xmlsitemap_node.test#L41
That node is unpublished in the debug output I get so the fact the test fails is good, I think. 

https://github.com/backdrop-contrib/xmlsitemap/blob/1.x-1.x/xmlsitemap_node/tests/xmlsitemap_node.test#L55
The node was now published but still failed. 

And https://github.com/backdrop-contrib/xmlsitemap/blob/1.x-1.x/xmlsitemap_node/tests/xmlsitemap_node.test#L64 somehow has an illegal choice on the publishing options?

<img width="978" alt="screen shot 2018-07-19 at 3 38 16 pm" src="https://user-images.githubusercontent.com/3640707/42966069-ed11b04e-8b69-11e8-968e-98d3e7fc1faa.png">

Locally, I can't see any errors when I'm manually testing but my new testing site has like four links in it.

**Comment by alexfinnarn** [comment]
nevermind, those fails make sense since the tests expect that the links are updated on node_update. So, the tests failing is actually a good thing. 

I will add to the test-related issues to modify those to reflect not updating on node_update.

**Comment by alexfinnarn** [comment]
merged into 1.x branch
