### ISSUE TITLE
Roadmap for next Release

### ISSUE THREAD

**Issue by alexfinnarn** [alexfinnarn/backdrop-xml-sitemap#78]
So far, #76 is the only issue committed, but I'd like to actually use https://github.com/alexfinnarn/testing-starter-scripts and https://github.com/alexfinnarn/testing-starter-template on a project. This would "fix" #17. 

I think the failures on the Simpletests can be commented out for now so that some Behat tests and the whole Simpletest suite could be run on every PR. 

#56 has a question in it, and #54 has a PR but also questions. I'm putting this issue out there for comment, but I think a few issues can be resolved in the next release. 

Thoughts on this @BWPanda @jenlampton?

**Comment by alexfinnarn** [comment]
I removed myself from maintaining the module in #79 so do as you please.

**Comment by laryn** [comment]
Closing this as outdated.
