### ISSUE TITLE
'page not found' notice for 'misc/arrow-desc.png'

### ISSUE THREAD

**Issue by alanmels** [alexfinnarn/backdrop-xml-sitemap#98]
Upon activation of the module the log shows the notice in subject. Apparently, that's because the [line 147](https://github.com/backdrop-contrib/xmlsitemap/blob/1f1369ae17926fb5ba027e9e186f98858d14d7ec/xmlsitemap.pages.inc#L147) of the `xmlsitemap.pages.inc` file contains Drupal 7 style path. In Backdrop that file has been moved into the `code` directory.

**Comment by alanmels** [comment]
Pardon, this seems to have been fixed in dev, however my website pulled the official version 1.x-1.0.6. Please release another version.

**Comment by alanmels** [comment]
Let me turn this into another similar issue found. After pulling the development version of the module, the website's log is now showing:

```
page not found
--
Monday, December 21, 2020 - 5:16am
altagrade
https://www.domain.tld/misc/arrow-desc.png
```

**Comment by laryn** [comment]
Thank you -- merged!
